export { default as Home } from "./Home";
export { default as Auth } from "./Auth";
export { default as Register } from "./Auth/register";
export { default as Problem } from "./Problems";
export { default as AProblem } from "./Problems/individualQuestion";
export { default as Leaderboard } from "./Leaderboard";
export { default as Profile } from "./Profile";
export { default as TermsCondition } from "./TermsCondition";
export { default as NotFoundPage } from "./Error/NotFoundPage";